server:
  port: 8080

spring:    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Password1234
    url: jdbc:mysql://localhost:3306/user-feedback 
    username: root

spring.jpa:
  database: MYSQL
  hibernate.ddl-auto: update
  show-sql: true
  properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"      